import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1770716024209 implements MigrationInterface {
    name = 'InitSchema1770716024209'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "claims" ("id" SERIAL NOT NULL, "import_job_id" character varying NOT NULL, "kode_rs" character varying(20), "kelas_rs" character varying(5), "kelas_rawat" character varying(5), "kode_tarif" character varying(5), "ptd" character varying(20), "admission_date" date, "discharge_date" date, "birth_date" date, "birth_weight" character varying(20), "sex" character varying(50), "discharge_status" character varying(150), "diaglist" character varying(150), "proclist" character varying(150), "adl1" character varying(150), "adl2" character varying(150), "in_sp" character varying(250), "in_sr" character varying(250), "in_si" character varying(250), "in_sd" character varying(250), "inacbg" character varying(250), "subacute" character varying(250), "chronic" character varying(250), "sp" character varying(250), "sr" character varying(250), "si" character varying(250), "sd" character varying(250), "deskripsi_inacbg" text, "tarif_inacbg" numeric(18,2), "tarif_subacute" numeric(18,2), "tarif_chronic" numeric(18,2), "deskripsi_sp" text, "tarif_sp" numeric(18,2), "deskripsi_sr" text, "tarif_sr" numeric(18,2), "deskripsi_si" text, "tarif_si" numeric(18,2), "deskripsi_sd" text, "tarif_sd" numeric(18,2), "total_tarif" numeric(18,2), "tarif_rs" numeric(18,2), "tarif_poli_eks" numeric(18,2), "los" integer, "icu_indikator" integer, "icu_los" integer, "vent_hour" integer, "nama_pasien" character varying(550), "mrn" character varying(20), "umur_tahun" integer, "umur_hari" integer, "dpjp" character varying(550), "sep" character varying(20), "nokartu" character varying(20), "payor_id" character varying(20), "coder_id" character varying(20), "versi_inacbg" character varying(50), "versi_grouper" character varying(20), "c1" text, "c2" text, "c3" text, "c4" text, "prosedur_non_bedah" numeric(18,2), "prosedur_bedah" numeric(18,2), "konsultasi" numeric(18,2), "tenaga_ahli" numeric(18,2), "keperawatan" numeric(18,2), "penunjang" numeric(18,2), "radiologi" numeric(18,2), "laboratorium" numeric(18,2), "pelayanan_darah" numeric(18,2), "rehabilitasi" numeric(18,2), "kamar_akomodasi" numeric(18,2), "rawat_intensif" numeric(18,2), "obat" numeric(18,2), "alkes" numeric(18,2), "bmhp" numeric(18,2), "sewa_alat" numeric(18,2), "obat_kronis" numeric(18,2), "obat_kemo" numeric(18,2), "severity_level" character varying(55), "raw_json" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_96c91970c0dcb2f69fdccd0a698" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "claims"`);
    }

}
