import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1771682096194 implements MigrationInterface {
    name = 'InitSchema1771682096194'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "username" character varying NOT NULL, "name" character varying NOT NULL, "password" character varying NOT NULL, "role" character varying NOT NULL, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "claim_rule_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "import_job_id" character varying NOT NULL, "triggered" boolean NOT NULL, "score_generated" integer NOT NULL DEFAULT '0', "message_generated" character varying NOT NULL, "evaluated_at" TIMESTAMP NOT NULL, "claimId" integer, "ruleId" uuid, CONSTRAINT "PK_34b8c0c6122659009bafd81db56" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "claims" ("id" SERIAL NOT NULL, "import_job_id" character varying NOT NULL, "kode_rs" character varying(500), "kelas_rs" character varying(500), "kelas_rawat" character varying(500), "kode_tarif" character varying(500), "ptd" character varying(500), "admission_date" date, "discharge_date" date, "birth_date" date, "birth_weight" character varying(500), "sex" character varying(500), "discharge_status" character varying(500), "diaglist" character varying(500), "proclist" character varying(500), "adl1" character varying(500), "adl2" character varying(500), "in_sp" character varying(500), "in_sr" character varying(500), "in_si" character varying(500), "in_sd" character varying(500), "inacbg" character varying(500), "subacute" character varying(500), "chronic" character varying(500), "sp" character varying(500), "sr" character varying(500), "si" character varying(500), "sd" character varying(500), "deskripsi_inacbg" text, "tarif_inacbg" numeric(18,2), "tarif_subacute" numeric(18,2), "tarif_chronic" numeric(18,2), "deskripsi_sp" text, "tarif_sp" numeric(18,2), "deskripsi_sr" text, "tarif_sr" numeric(18,2), "deskripsi_si" text, "tarif_si" numeric(18,2), "deskripsi_sd" text, "tarif_sd" numeric(18,2), "total_tarif" numeric(18,2), "tarif_rs" numeric(18,2), "tarif_poli_eks" numeric(18,2), "los" integer, "icu_indikator" integer, "icu_los" integer, "vent_hour" integer, "nama_pasien" character varying(500), "mrn" character varying(500), "umur_tahun" integer, "umur_hari" integer, "dpjp" character varying(500), "sep" character varying(500), "nokartu" character varying(500), "payor_id" character varying(500), "coder_id" character varying(500), "versi_inacbg" character varying(500), "versi_grouper" character varying(500), "c1" text, "c2" text, "c3" text, "c4" text, "prosedur_non_bedah" numeric(18,2), "prosedur_bedah" numeric(18,2), "konsultasi" numeric(18,2), "tenaga_ahli" numeric(18,2), "keperawatan" numeric(18,2), "penunjang" numeric(18,2), "radiologi" numeric(18,2), "laboratorium" numeric(18,2), "pelayanan_darah" numeric(18,2), "rehabilitasi" numeric(18,2), "kamar_akomodasi" numeric(18,2), "rawat_intensif" numeric(18,2), "obat" numeric(18,2), "alkes" numeric(18,2), "bmhp" numeric(18,2), "sewa_alat" numeric(18,2), "obat_kronis" numeric(18,2), "obat_kemo" numeric(18,2), "severity_level" character varying(500), "kategori" character varying(50), "cmg" character varying(50), "tipe_kasus" character varying(50), "raw_json" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_96c91970c0dcb2f69fdccd0a698" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hospitals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "code" character varying NOT NULL, "name" character varying NOT NULL, "class" character varying NOT NULL, "address" character varying NOT NULL, "phone" character varying, CONSTRAINT "UQ_21e0a14f85fd90af5c34cdc7d6c" UNIQUE ("code"), CONSTRAINT "PK_02738c80d71453bc3e369a01766" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rule_actions_action_type_enum" AS ENUM('WARNING', 'SCORE_ADD', 'BLOCK', 'FLAG')`);
        await queryRunner.query(`CREATE TABLE "rule_actions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "action_type" "public"."rule_actions_action_type_enum" NOT NULL, "message_template" text, "score_override" integer, "severity_override" character varying, "ruleId" uuid, CONSTRAINT "PK_bb97640f29f414e475b45c90b2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rule_conditions_operator_enum" AS ENUM('EQUAL', 'NOT_EQUAL', 'GREATER_THAN', 'LESS_THAN', 'CONTAINS', 'NOT_CONTAINS', 'BETWEEN')`);
        await queryRunner.query(`CREATE TABLE "rule_conditions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "field_name" character varying(100) NOT NULL, "operator" "public"."rule_conditions_operator_enum" NOT NULL, "value" text NOT NULL, "value_type" character varying NOT NULL DEFAULT 'STRING', "ruleId" uuid, "groupId" uuid, CONSTRAINT "PK_8ff5364b054affe0bad08f1ae9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8dedd16298bad966d010de2cae" ON "rule_conditions" ("field_name") `);
        await queryRunner.query(`CREATE TYPE "public"."rule_condition_groups_logical_operator_enum" AS ENUM('AND', 'OR')`);
        await queryRunner.query(`CREATE TABLE "rule_condition_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "logical_operator" "public"."rule_condition_groups_logical_operator_enum" NOT NULL, "order_index" integer NOT NULL DEFAULT '0', "ruleId" uuid, "parentId" uuid, CONSTRAINT "PK_7303a755c069f464ae93b9af459" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rules_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(200) NOT NULL, "description" text, "category" character varying(100) NOT NULL, "severity_level" character varying(20) NOT NULL, "base_score" integer NOT NULL DEFAULT '0', "status" "public"."rules_status_enum" NOT NULL DEFAULT 'DRAFT', "version" integer NOT NULL DEFAULT '1', "effective_start_date" date, "effective_end_date" date, "hospitalId" uuid, CONSTRAINT "PK_10fef696a7d61140361b1b23608" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ded181ac4b18aea587ccfd1443" ON "rules" ("status", "effective_start_date") `);
        await queryRunner.query(`CREATE TABLE "procedures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "code" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_e7775bab78f27b4c47580b6cb4b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "overstays" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "category" character varying(500) NOT NULL, "value_start" integer NOT NULL, "value_end" integer NOT NULL, "description" character varying(500), "is_overstay" boolean NOT NULL DEFAULT true, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_0b322122b4723fabc5933426e80" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "diagnoses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "code" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_d1bfabf423f99c537817e6ad244" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "import_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "filename" character varying NOT NULL, "status" character varying NOT NULL, "total_records" integer NOT NULL, "processed_records" integer NOT NULL, "progress" integer NOT NULL DEFAULT '0', "started_at" TIMESTAMP, "completed_at" TIMESTAMP, CONSTRAINT "PK_4d206c602f173f98e4bb85819a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "procedure_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "import_job_id" character varying NOT NULL, "claim_id" integer NOT NULL, "procedure_code" character varying NOT NULL, CONSTRAINT "PK_21ffbe55752759c12dc7ebcb2d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "diagnose_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "import_job_id" character varying NOT NULL, "claim_id" integer NOT NULL, "diagnose_code" character varying NOT NULL, CONSTRAINT "PK_915139ec816f0575306d5f3db5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "claim_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "import_job_id" character varying NOT NULL, "claim_id" integer NOT NULL, "group_result" character varying NOT NULL, "sub_group_result" character varying, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07f1738ab64e2e30a207a8ae255" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "claim_rule_results" ADD CONSTRAINT "FK_738f21b04c3beb9a9c24492f22f" FOREIGN KEY ("claimId") REFERENCES "claims"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "claim_rule_results" ADD CONSTRAINT "FK_8a11986df8f6d8b05baf456acce" FOREIGN KEY ("ruleId") REFERENCES "rules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_actions" ADD CONSTRAINT "FK_33b0c91a463427104c299654853" FOREIGN KEY ("ruleId") REFERENCES "rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_conditions" ADD CONSTRAINT "FK_77f0ebb17bd9c95e18e4b39c6d7" FOREIGN KEY ("ruleId") REFERENCES "rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_conditions" ADD CONSTRAINT "FK_9f86538a978f05a3d90fb0e9357" FOREIGN KEY ("groupId") REFERENCES "rule_condition_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_condition_groups" ADD CONSTRAINT "FK_716ba9e1a1bdb01415070395329" FOREIGN KEY ("ruleId") REFERENCES "rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_condition_groups" ADD CONSTRAINT "FK_79d35c438c3afdbda1472c6c07b" FOREIGN KEY ("parentId") REFERENCES "rule_condition_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "FK_01f5554a7eb3c03f016cd9d0a50" FOREIGN KEY ("hospitalId") REFERENCES "hospitals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rules" DROP CONSTRAINT "FK_01f5554a7eb3c03f016cd9d0a50"`);
        await queryRunner.query(`ALTER TABLE "rule_condition_groups" DROP CONSTRAINT "FK_79d35c438c3afdbda1472c6c07b"`);
        await queryRunner.query(`ALTER TABLE "rule_condition_groups" DROP CONSTRAINT "FK_716ba9e1a1bdb01415070395329"`);
        await queryRunner.query(`ALTER TABLE "rule_conditions" DROP CONSTRAINT "FK_9f86538a978f05a3d90fb0e9357"`);
        await queryRunner.query(`ALTER TABLE "rule_conditions" DROP CONSTRAINT "FK_77f0ebb17bd9c95e18e4b39c6d7"`);
        await queryRunner.query(`ALTER TABLE "rule_actions" DROP CONSTRAINT "FK_33b0c91a463427104c299654853"`);
        await queryRunner.query(`ALTER TABLE "claim_rule_results" DROP CONSTRAINT "FK_8a11986df8f6d8b05baf456acce"`);
        await queryRunner.query(`ALTER TABLE "claim_rule_results" DROP CONSTRAINT "FK_738f21b04c3beb9a9c24492f22f"`);
        await queryRunner.query(`DROP TABLE "claim_results"`);
        await queryRunner.query(`DROP TABLE "diagnose_transactions"`);
        await queryRunner.query(`DROP TABLE "procedure_transactions"`);
        await queryRunner.query(`DROP TABLE "import_jobs"`);
        await queryRunner.query(`DROP TABLE "diagnoses"`);
        await queryRunner.query(`DROP TABLE "overstays"`);
        await queryRunner.query(`DROP TABLE "procedures"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ded181ac4b18aea587ccfd1443"`);
        await queryRunner.query(`DROP TABLE "rules"`);
        await queryRunner.query(`DROP TYPE "public"."rules_status_enum"`);
        await queryRunner.query(`DROP TABLE "rule_condition_groups"`);
        await queryRunner.query(`DROP TYPE "public"."rule_condition_groups_logical_operator_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8dedd16298bad966d010de2cae"`);
        await queryRunner.query(`DROP TABLE "rule_conditions"`);
        await queryRunner.query(`DROP TYPE "public"."rule_conditions_operator_enum"`);
        await queryRunner.query(`DROP TABLE "rule_actions"`);
        await queryRunner.query(`DROP TYPE "public"."rule_actions_action_type_enum"`);
        await queryRunner.query(`DROP TABLE "hospitals"`);
        await queryRunner.query(`DROP TABLE "claims"`);
        await queryRunner.query(`DROP TABLE "claim_rule_results"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
