import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1771254233347 implements MigrationInterface {
    name = 'InitSchema1771254233347'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "name" character varying NOT NULL, "password" character varying NOT NULL, "role" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "description" text, "category" character varying(100), "severity_level" character varying(50), "score" integer NOT NULL DEFAULT '0', "expression" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_10fef696a7d61140361b1b23608" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "overstays" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category" character varying(500) NOT NULL, "value_start" integer NOT NULL, "value_end" integer NOT NULL, "description" character varying(500), "is_overstay" boolean NOT NULL DEFAULT true, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0b322122b4723fabc5933426e80" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hospitals" ("kode_rs" character varying NOT NULL, "name" character varying NOT NULL, "kelas_rs" character varying NOT NULL, "address" character varying NOT NULL, "phone" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5dc9920b687224ebbaebe278a05" PRIMARY KEY ("kode_rs"))`);
        await queryRunner.query(`CREATE TABLE "procedure_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "claim_id" integer NOT NULL, "procedure_code" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_21ffbe55752759c12dc7ebcb2d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "import_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filename" character varying NOT NULL, "status" character varying NOT NULL, "total_records" integer NOT NULL, "processed_records" integer NOT NULL, "progress" integer NOT NULL DEFAULT '0', "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4d206c602f173f98e4bb85819a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "diagnose_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "claim_id" integer NOT NULL, "diagnose_code" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_915139ec816f0575306d5f3db5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "claim_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "import_job_id" character varying NOT NULL, "claim_id" integer NOT NULL, "group_result" character varying NOT NULL, "sub_group_result" character varying, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07f1738ab64e2e30a207a8ae255" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "claims" ("id" SERIAL NOT NULL, "import_job_id" character varying NOT NULL, "kode_rs" character varying(500), "kelas_rs" character varying(500), "kelas_rawat" character varying(500), "kode_tarif" character varying(500), "ptd" character varying(500), "admission_date" date, "discharge_date" date, "birth_date" date, "birth_weight" character varying(500), "sex" character varying(500), "discharge_status" character varying(500), "diaglist" character varying(500), "proclist" character varying(500), "adl1" character varying(500), "adl2" character varying(500), "in_sp" character varying(500), "in_sr" character varying(500), "in_si" character varying(500), "in_sd" character varying(500), "inacbg" character varying(500), "subacute" character varying(500), "chronic" character varying(500), "sp" character varying(500), "sr" character varying(500), "si" character varying(500), "sd" character varying(500), "deskripsi_inacbg" text, "tarif_inacbg" numeric(18,2), "tarif_subacute" numeric(18,2), "tarif_chronic" numeric(18,2), "deskripsi_sp" text, "tarif_sp" numeric(18,2), "deskripsi_sr" text, "tarif_sr" numeric(18,2), "deskripsi_si" text, "tarif_si" numeric(18,2), "deskripsi_sd" text, "tarif_sd" numeric(18,2), "total_tarif" numeric(18,2), "tarif_rs" numeric(18,2), "tarif_poli_eks" numeric(18,2), "los" integer, "icu_indikator" integer, "icu_los" integer, "vent_hour" integer, "nama_pasien" character varying(500), "mrn" character varying(500), "umur_tahun" integer, "umur_hari" integer, "dpjp" character varying(500), "sep" character varying(500), "nokartu" character varying(500), "payor_id" character varying(500), "coder_id" character varying(500), "versi_inacbg" character varying(500), "versi_grouper" character varying(500), "c1" text, "c2" text, "c3" text, "c4" text, "prosedur_non_bedah" numeric(18,2), "prosedur_bedah" numeric(18,2), "konsultasi" numeric(18,2), "tenaga_ahli" numeric(18,2), "keperawatan" numeric(18,2), "penunjang" numeric(18,2), "radiologi" numeric(18,2), "laboratorium" numeric(18,2), "pelayanan_darah" numeric(18,2), "rehabilitasi" numeric(18,2), "kamar_akomodasi" numeric(18,2), "rawat_intensif" numeric(18,2), "obat" numeric(18,2), "alkes" numeric(18,2), "bmhp" numeric(18,2), "sewa_alat" numeric(18,2), "obat_kronis" numeric(18,2), "obat_kemo" numeric(18,2), "severity_level" character varying(500), "kategori" character varying(50), "cmg" character varying(50), "tipe_kasus" character varying(50), "raw_json" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_96c91970c0dcb2f69fdccd0a698" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "claims"`);
        await queryRunner.query(`DROP TABLE "claim_results"`);
        await queryRunner.query(`DROP TABLE "diagnose_transactions"`);
        await queryRunner.query(`DROP TABLE "import_jobs"`);
        await queryRunner.query(`DROP TABLE "procedure_transactions"`);
        await queryRunner.query(`DROP TABLE "hospitals"`);
        await queryRunner.query(`DROP TABLE "overstays"`);
        await queryRunner.query(`DROP TABLE "rules"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
